In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from scipy.sparse import hstack
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
np.random.seed(12345)

Using TensorFlow backend.


In [2]:
train=pd.read_csv('train.csv')
test = pd.read_csv('train.csv')

FileNotFoundError: [Errno 2] File b'train (3) (1) (3) (2).csv' does not exist: b'train (3) (1) (3) (2).csv'

In [624]:
train.head()

id  App Version Code  App Version Name  \
0  b817b0f0-a2f8-4c9d-a5f6-d3fbf8b1d7e9               NaN               NaN   
1  c7844e8f-56c1-487b-ae3e-df2fdf4c1767              43.0              2.30   
2  93ff57f7-9e02-4fa9-b779-3db82b8af0a4              52.0              2.12   
3  df2dcdef-c09a-4f35-afab-e1231d3fec9a              62.0              2.21   
4  11f8f968-4cec-4424-8427-9709ab05b5be              69.0              2.28   

                                         Review Text  Review Title  \
0                   Very bad wallet balance not use.           NaN   
1  Froud app i recharge 199 but not done also sen...           NaN   
2                       Waste to write comments also  Waste no use   
3                                           Nice apo           NaN   
4                                      Good nice app           NaN   

   Star Rating  
0            1  
1            1  
2            2  
3            5  
4            5

In [625]:
train['STORY']=train['Review Text'].str.replace(':\)','emojihappy1')
train['STORY']=train['STORY'].str.replace(':P','emojihappy2')
train['STORY']=train['STORY'].str.replace(':p','emojihappy3')
train['STORY']=train['STORY'].str.replace(':>','emojihappy4')
train['STORY']=train['STORY'].str.replace(':3','emojihappy5')
train['STORY']=train['STORY'].str.replace(':D','emojihappy6')
train['STORY']=train['STORY'].str.replace('XD','emojihappy7')
train['STORY']=train['STORY'].str.replace('<3','emojihappy8')
train['STORY']=train['STORY'].str.replace(':\(','emojisad9')
train['STORY']=train['STORY'].str.replace(':<','emojisad10')
train['STORY']=train['STORY'].str.replace('>:\(','emojisad11')
train['STORY']=train['STORY'].str.replace('(@)\w+','mentiontoken')
train['STORY']=train['STORY'].str.replace('http(s)*:(\S)*','linktoken')
train['STORY']=train['STORY'].str.replace('[^A-Za-z0-9(),!?\'\`]',' ')
train['STORY']=train['STORY'].str.replace('[^\w\s]','')

In [626]:
train['STORY1']=train['Review Title'].str.replace(':\)','emojihappy1')
train['STORY1']=train['STORY1'].str.replace(':P','emojihappy2')
train['STORY1']=train['STORY1'].str.replace(':p','emojihappy3')
train['STORY1']=train['STORY1'].str.replace(':>','emojihappy4')
train['STORY1']=train['STORY1'].str.replace(':3','emojihappy5')
train['STORY1']=train['STORY1'].str.replace(':D','emojihappy6')
train['STORY1']=train['STORY1'].str.replace('XD','emojihappy7')
train['STORY1']=train['STORY1'].str.replace('<3','emojihappy8')
train['STORY1']=train['STORY1'].str.replace(':\(','emojisad9')
train['STORY1']=train['STORY1'].str.replace(':<','emojisad10')
train['STORY1']=train['STORY1'].str.replace('>:\(','emojisad11')
train['STORY1']=train['STORY1'].str.replace('(@)\w+','mentiontoken')
train['STORY1']=train['STORY1'].str.replace('http(s)*:(\S)*','linktoken')
train['STORY1']=train['STORY1'].str.replace('[^A-Za-z0-9(),!?\'\`]',' ')
train['STORY1']=train['STORY1'].str.replace('[^\w\s]','')

In [627]:
y = train['Star Rating']
y1=train['Star Rating']
del train['Star Rating']
encoder = LabelEncoder()
encoder.fit(y)
encoded_Y = encoder.transform(y)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(encoded_Y)
dummy_y=pd.DataFrame(dummy_y)
dummy_y.columns=['Level_0','Level_1','Level_2','Level_3','Level_4']

In [628]:
train1=pd.concat([train['STORY'], dummy_y], axis=1)

In [629]:
train1.head()

STORY  Level_0  Level_1  \
0                   Very bad wallet balance not use       1.0      0.0   
1  Froud app i recharge 199 but not done also sen...      1.0      0.0   
2                       Waste to write comments also      0.0      1.0   
3                                           Nice apo      0.0      0.0   
4                                      Good nice app      0.0      0.0   

   Level_2  Level_3  Level_4  
0      0.0      0.0      0.0  
1      0.0      0.0      0.0  
2      0.0      0.0      0.0  
3      0.0      0.0      1.0  
4      0.0      0.0      1.0

In [630]:
class_names = ['Level_0','Level_1','Level_2','Level_3','Level_4']

In [631]:
test['STORY']=test['Review Text'].str.replace(':\)','emojihappy1')
test['STORY']=test['STORY'].str.replace(':P','emojihappy2')
test['STORY']=test['STORY'].str.replace(':p','emojihappy3')
test['STORY']=test['STORY'].str.replace(':>','emojihappy4')
test['STORY']=test['STORY'].str.replace(':3','emojihappy5')
test['STORY']=test['STORY'].str.replace(':D','emojihappy6')
test['STORY']=test['STORY'].str.replace('XD','emojihappy7')
test['STORY']=test['STORY'].str.replace('<3','emojihappy8')
test['STORY']=test['STORY'].str.replace(':\(','emojisad9')
test['STORY']=test['STORY'].str.replace(':<','emojisad10')
test['STORY']=test['STORY'].str.replace('>:\(','emojisad11')
test['STORY']=test['STORY'].str.replace('(@)\w+','mentiontoken')
test['STORY']=test['STORY'].str.replace('http(s)*:(\S)*','linktoken')
test['STORY']=test['STORY'].str.replace('[^A-Za-z0-9(),!?\'\`]',' ')
test['STORY']=test['STORY'].str.replace('[^\w\s]','')

In [632]:
test['STORY1']=test['Review Title'].str.replace(':\)','emojihappy1')
test['STORY1']=test['STORY1'].str.replace(':P','emojihappy2')
test['STORY1']=test['STORY1'].str.replace(':p','emojihappy3')
test['STORY1']=test['STORY1'].str.replace(':>','emojihappy4')
test['STORY1']=test['STORY1'].str.replace(':3','emojihappy5')
test['STORY1']=test['STORY1'].str.replace(':D','emojihappy6')
test['STORY1']=test['STORY1'].str.replace('XD','emojihappy7')
test['STORY1']=test['STORY1'].str.replace('<3','emojihappy8')
test['STORY1']=test['STORY1'].str.replace(':\(','emojisad9')
test['STORY1']=test['STORY1'].str.replace(':<','emojisad10')
test['STORY1']=test['STORY1'].str.replace('>:\(','emojisad11')
test['STORY1']=test['STORY1'].str.replace('(@)\w+','mentiontoken')
test['STORY1']=test['STORY1'].str.replace('http(s)*:(\S)*','linktoken')
test['STORY1']=test['STORY1'].str.replace('[^A-Za-z0-9(),!?\'\`]',' ')
test['STORY1']=test['STORY1'].str.replace('[^\w\s]','')

In [633]:
test['index1'] = test.index
train['index1'] = train.index

In [634]:
train_text1 = train['STORY']
train_text2 = train['STORY1']


test_text1 = test['STORY']
test_text2 = test['STORY1']


all_text = pd.concat([train_text1,train_text2,test_text1,test_text2])


all_text=all_text.fillna('None')
train_text1=train_text1.fillna('None')
test_text1=test_text1.fillna('None')

train_text2=train_text2.fillna('None')
test_text2=test_text2.fillna('None')

In [635]:
def predict_one(x, y, xt):
    c = LogisticRegression(C=8, class_weight='balanced') #4/6
    c.fit(x, y)
    #y_pred = c.predict_proba(xt)
    y_pred = c.predict_proba(x)
    idx = list(c.classes_).index(1)
    return y_pred[:, idx]

In [636]:
word_vectorizer = TfidfVectorizer(
    sublinear_tf=True,
    strip_accents='unicode',
    analyzer='word',
    token_pattern=r'\w{1,}',
    stop_words='english',
    ngram_range=(1, 3), #(1,1)
    max_features=10000)
word_vectorizer.fit(all_text)
train_word_features1 = word_vectorizer.transform(train_text1)
test_word_features1 = word_vectorizer.transform(test_text1)

train_word_features2 = word_vectorizer.transform(train_text2)
test_word_features2 = word_vectorizer.transform(test_text2)

C:\Users\pf416e\AppData\Local\Continuum\Anaconda3_v1\lib\site-packages\sklearn\feature_extraction\text.py:1059: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):


In [637]:
char_vectorizer = TfidfVectorizer(
    sublinear_tf=True,
    strip_accents='unicode',
    analyzer='char',
    stop_words='english',
    ngram_range=(2, 6),
    max_features=90000) 
char_vectorizer.fit(all_text)
train_char_features1 = char_vectorizer.transform(train_text1)
test_char_features1 = char_vectorizer.transform(test_text1)

train_char_features2 = char_vectorizer.transform(train_text2)
test_char_features2 = char_vectorizer.transform(test_text2)

C:\Users\pf416e\AppData\Local\Continuum\Anaconda3_v1\lib\site-packages\sklearn\feature_extraction\text.py:1059: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):


In [638]:
train_char_features=hstack([train_char_features1, train_char_features2])
test_char_features=hstack([test_char_features1,test_char_features2])

train_word_features=hstack([train_word_features1,train_word_features2])
test_word_features=hstack([test_word_features1,test_word_features2])


train_features = hstack([train_char_features1, train_word_features1,train_char_features2, train_word_features2])
test_features = hstack([test_char_features1, test_word_features1,test_char_features2, test_word_features2])

In [639]:
sub_c = pd.DataFrame({'id': train['index1']})
sub_w = pd.DataFrame({'id': train['index1']})
sub_j = pd.DataFrame({'id': train['index1']})
sub_mean = pd.DataFrame({'id': train['index1']})
sub_max = pd.DataFrame({'id': train['index1']})

In [640]:
for t in class_names:
    y = train1[t].values
    y_pred_c = predict_one(train_char_features, y, test_char_features)
    y_pred_w = predict_one(train_word_features, y, test_word_features)
    y_pred_j = predict_one(train_features, y, test_features)
    
    sub_c[t] = y_pred_c
    sub_w[t] = y_pred_w
    sub_j[t] = y_pred_j #best
    sub_mean[t] = 0.5 * (y_pred_c + y_pred_w)
    sub_max[t] = np.maximum(y_pred_c, y_pred_w)
    print('predict {}'.format(t))

predict Level_0
predict Level_1
predict Level_2
predict Level_3
predict Level_4


In [641]:
del sub_j['id']
pred=sub_j.values
labels = np.argmax(pred, axis=-1)
labels1=labels+1

from sklearn.metrics import accuracy_score
print(accuracy_score(y1, labels1))

print(confusion_matrix(y1, labels1))

0.9487089408044967
[[1782    2    0    2    2]
 [   1  147    1    0    5]
 [   1    0  198    2   16]
 [   1    1    4  437  168]
 [   8    0   15   63 2837]]


In [642]:
del sub_mean['id']
pred=sub_mean.values
labels = np.argmax(pred, axis=-1)
labels1=labels+1

from sklearn.metrics import accuracy_score
print(accuracy_score(y1, labels1))

print(confusion_matrix(y1, labels1))

0.9425610398735289
[[1777    2    0    2    7]
 [   1  146    1    0    6]
 [   1    0  197    1   18]
 [   3    1    5  420  182]
 [  17    0   16   64 2826]]


In [643]:
del sub_w['id']
pred=sub_w.values
labels = np.argmax(pred, axis=-1)
labels1=labels+1

from sklearn.metrics import accuracy_score
print(accuracy_score(y1, labels1))

print(confusion_matrix(y1, labels1))

0.9265764974530125
[[1753    5    5    4   21]
 [   1  143    1    0    9]
 [   3    0  186    0   28]
 [   6    1    7  397  200]
 [  19    1   29   78 2796]]


In [644]:
del sub_c['id']
pred=sub_c.values
labels = np.argmax(pred, axis=-1)
labels1=labels+1

print(accuracy_score(y1, labels1))

print(confusion_matrix(y1, labels1))

0.9423853855612155
[[1780    3    0    2    3]
 [   1  147    1    0    5]
 [   2    0  197    2   16]
 [   2    1    4  426  178]
 [  19    0   15   74 2815]]


In [645]:
del sub_max['id']
pred=sub_max.values
labels = np.argmax(pred, axis=-1)
labels1=labels+1

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
print(accuracy_score(y1, labels1))

print(confusion_matrix(y1, labels1))

0.9381696820656947
[[1771    4    4    3    6]
 [   1  147    1    0    5]
 [   3    0  195    1   18]
 [   4    1    8  412  186]
 [  18    1   24   64 2816]]
